name: Test1

on:
  push:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
